# docker-compose.override.yml

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - ./:/app
    ports:
      - "${APP_PORT}:8000"
    environment:
      - DEBUG=1
      - DJANGO_ENV=development

  nginx:
    ports: []
    command: ["nginx", "-g", "daemon off;"]