# docker-compose.override.yml

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${APP_PORT}:8000"
    environment:
      - DEBUG=True
      - DJANGO_ENV=development
    volumes:
      - ./theme/static:/app/theme/static