# docker-compose.override.yml

services:
  web:
    command: python manage.py tailwind dev 0.0.0.0:${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DEBUG=True
      - DJANGO_ENV=development

  nginx:
    ports: []
    command: ["nginx", "-g", "daemon off;"]